language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk11
  - openjdk13

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  